server:
 port: 8080
 
# DB Config
spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://laypact.clsjimf1dwao.us-east-1.rds.amazonaws.com:5432/postgres
  username: root
  password: lay20693091
  
  devtools :
    restart :
      enabled: true
 mvc:
  hiddenmethod.filter.enabled: true
  
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:   
   ddl-auto: update
  properties:
   hibernate:
    format_sql: true #운영에서는 false 처리
    highlight_sql: true #운영에서는 false 처리
    use_sql_comments: true #운영에서는 false 처리    

 thymeleaf:
  enabled: true
  cache: false
  prefix: classpath:/templates/
  suffix: .html

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
    
file:
  upload:
    location: /Users/ck/