# DB Config
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:thin:@postgres://sstarkkm:hzYxITuwojWE0t6mYkYidiKQqSEu1yiW@tiny.db.elephantsql.com/sstarkkm
    username: sstarkkm
    password: hzYxITuwojWE0t6mYkYidiKQqSEu1yiW
    
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    

logging:
  level:
    org:
     Springframework:
      jdbc: debug
      
     hibernate:
      type:
       descriptor:
        sql:
         basicBinder: TRACE
      SQL: DEBUG

  
